# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foodie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
  api:
    image: books-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/foodie
